### ISSUE TITLE
network codes seems not same with codes in StarGanv2VC

### ISSUE THREAD

**Issue by superhg** [yl4579/PitchExtractor#2]
![image](https://user-images.githubusercontent.com/6316449/174007641-ac756c2a-3cef-40bc-8c77-3d973289c663.png)

**Comment by yl4579** [comment]
Because for StarGANv2-VC we do not need to estimate the actual F0 curve, but only the intermediate features. For training, we do need to get the F0 curves and silence.

**Comment by superhg** [comment]
ok, thanks!!!
