### ISSUE TITLE
Num_class must be 1?

### ISSUE THREAD

**Issue by chiaki-luo** [yl4579/PitchExtractor#5]
It seems that the num_class must be one, otherwise I need to change the code of L1_loss, so if I have two classes, should I use class=1 or change the loss code?
Thank you for your help!

**Comment by yl4579** [comment]
Sorry for the late reply. Yes the `num_class` must be 1, because we are only predicting a time series (F0). The original JDC net was designed to predict the note classes for MIDI transcription, but here we used it for F0 curve prediction only.
