### ISSUE TITLE
About checkpoint file format

### ISSUE THREAD

**Issue by charliezjw** [yl4579/PitchExtractor#6]
Using the codebase, the checkpoint is saved as "epoch_00100.pth", while the StarGANv2-VC's default checkpoint file is "bst.t7". They have different extensions.
When loading in the "epoch_00100.pth" checkpoint in StarGANv2-VC, it throws me an error
`  File "/opt/conda/envs/star/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/star/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/star/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/star/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/charlie_babelcast_com/github/StarGANv2-VC/train.py", line 90, in main
    params = torch.load(F0_path, map_location='cpu')['net']
KeyError: 'net
`
How can I save the correct .t7 file?
Thank you!

**Comment by charliezjw** [comment]
My bad, found the problem.

**Comment by christopherohit** [comment]
@charliezjw Sorry but i got same error but i don't found any way to solve it

**Comment by ziyaad30** [comment]
Change the function in StyleTTS models:

https://github.com/yl4579/StyleTTS/blob/eac67158fd21578ea950ff4d6734bf6e6434b6b5/models.py#L647


`def load_F0_models(path):
    # load F0 model

    F0_model = JDCNet(num_class=1, seq_len=192)
    # params = torch.load(path, map_location='cpu')['net']
    params = torch.load(path, map_location='cpu')['model']
    F0_model.load_state_dict(params)
    _ = F0_model.train()

    return F0_model`
